TOP ?= ../../..
PROG_AMIGA  =
PROG_AMIGA += doublebuffer
PROG_AMIGA += dualplayfield
PROG_AMIGA += newlookscreen
PROG_AMIGA += publicscreen
PROG_AMIGA += pubscreenbeep
PROG_AMIGA += screen34to37
PROG_CLIB   = clonescreen
include $(TOP)/rules.mk
