TOP ?= ../..
PROG_AMIGA  =
PROG_AMIGA += a2d
PROG_AMIGA += tag1
PROG_CLIB   =
PROG_CLIB  += istr
PROG_FIXME  =
PROG_FIXME += uptime # Uses SAS C getreg() for UDivMod32 second arg.
PROG_FIXME += hooks1 # Needs assembly.
include $(TOP)/rules.mk

