TOP ?= ../../..
PROG_FIXME  =
# Calling convention for callbacks
PROG_FIXME += collide
# chip keyword
PROG_FIXME += anim
PROG_FIXME += bob
PROG_FIXME += ssprite
PROG_FIXME += vsprite

include $(TOP)/rules.mk

