TOP ?= ../..
PROG_AMIGA = Audio
# Source not complete, missing some iff headers available in the 3.1 NDK
# (Examples2/). See also ../iff/Read_Me of the RKRM examples.
UNSUPPORTED = audio_8svx
include $(TOP)/rules.mk

